version: '3.8'
services:
  app:
    container_name: media4U
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media4U:/media4U
    ports:
      - "8000:8000"
    restart: always
volumes:
  media4U: